name: athkar_app
description: "تطبيق أذكار إسلامية مع مواقيت الصلاة واتجاه القبلة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- State Management ---
  provider: ^6.1.5
  get_it: ^8.0.3

  # --- Storage ---
  shared_preferences: ^2.2.2

  # --- Notifications ---
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  # --- Firebase (Core & Messaging only) ---
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_remote_config: ^6.1.0
  firebase_analytics: ^12.0.3           # جديد
  firebase_crashlytics: ^5.0.3          # جديد
  firebase_performance: ^0.11.1       # جديد
  firebase_in_app_messaging: ^0.9.0


  # --- Location & Prayer ---
  adhan: ^2.0.0+1
  geocoding: ^4.0.0
  permission_handler: ^11.4.0

  # --- Date & Time ---
  intl: ^0.19.0        # مطلوب من Flutter SDK
  hijri: ^3.0.0
  flutter_timezone: ^4.1.1

  # --- Utilities ---
  share_plus: ^7.2.2
  battery_plus: ^6.2.1
  in_app_review: ^2.0.10
  concentric_transition: ^1.0.3
  lottie: ^3.3.1
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.1
  flutter_screenutil: ^5.9.3

  # --- Qibla & Location ---
  flutter_qiblah: ^3.1.0+1
  geolocator: ^13.0.2  # متوافق مع flutter_qiblah ^3.1.0+1

  # --- Development & Performance ---
  logger: ^2.4.0
  flutter_islamic_icons: ^1.0.2
  connectivity_plus: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Development Tools ---
  flutter_lints: ^5.0.0
  leak_tracker: ^10.0.5
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.4

# إعدادات أيقونة التطبيق - الأندرويد فقط
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/ذكرني.png"
  
  # Adaptive Icon للأندرويد الحديث (Android 8.0+)
  adaptive_icon_foreground: "assets/icon/ذكرني.png"
  adaptive_icon_background: "#FFFFFF"



flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/animations/
    - assets/icon/


  fonts:
    # خط القاهرة - الخط الأساسي للواجهة
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    
    # خط أميري - للنصوص الدينية العامة
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    
    # خط أميري قرآن - مُحسّن للآيات القرآنية
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran.ttf
          weight: 400
    
