// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Android Only - iOS and Web are not supported

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'This app only supports Android platform. Web is not supported.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'This app only supports Android platform. '
          'Current platform (${defaultTargetPlatform.name}) is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBduWVF2EBK_RG1iq8voaMzsBTbCLB1x5Y',
    appId: '1:627917894269:android:0a6d4b051a641d69b7b714',
    messagingSenderId: '627917894269',
    projectId: 'athkar-app-7074e',
    storageBucket: 'athkar-app-7074e.firebasestorage.app',
  );
}